# Configuraci贸n de Netlify para FutCamisRetros

[build]
  publish = "dist"
  command = "export NODE_OPTIONS='--max-old-space-size=4096' && npm run build"

[build.environment]
  NODE_VERSION = "18.20.2"
  NPM_FLAGS = "--no-audit --no-fund"

# Redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirecciones para SEO
[[redirects]]
  from = "/camisetas"
  to = "/catalog"
  status = 301

[[redirects]]
  from = "/camisetas-retro"
  to = "/league/retro"
  status = 301

[[redirects]]
  from = "/camisetas-baratas"
  to = "/catalog?sort=price-asc"
  status = 301

# Configuraci贸n de plugins
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
  buildDir = "dist"
  prettyURLs = true
  trailingSlash = false

[[plugins]]
  package = "netlify-plugin-cache"
  
  [plugins.inputs]
  paths = [
    "node_modules/.cache",
    "dist"
  ]

# Configuraci贸n de optimizaci贸n
[build.processing]
  skip_processing = false

[build.processing.js]
  bundle = true
  minify = false

[build.processing.css]
  bundle = true
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false